### ISSUE TITLE
Return all standard variable information in query

### ISSUE THREAD

**Issue by brandomr** [mintproject/MINT-DataCatalog-Public#10]
The following query returns information about a standard variable based on a search using it's ID. However, it does not return the standard variables URI. This is key information that should be returned along with the name/description/metadata.

```
q = {
  "variable_ids__in": [SOME_ID_HERE]
}

resp = requests.post(f"{url}/variables/variables_standard_variables",
                     headers=request_headers,
                     json=q).json()
```

**Comment by dnfeldman** [comment]
@brandomr I updated the endpoint to return the following for each standard_variable:
`id`, `name`, `ontology`, `uri`, `description` (all prepended with `standard_variable_` to distinguish them from other keys in the response body
