### ISSUE TITLE
SVO names for River Change Dataset

### ISSUE THREAD

**Issue by ankushkhandelwal** [mintproject/MINT-DataCatalog-Public#9]
**Dataset Name**: River Change Dataset
**Dataset Source**: http://umnlcc.cs.umn.edu/RiverChangeDataset/info.html
**Sample File URL**: http://umnlcc.cs.umn.edu/RiverChangeDataset/box-224-sec-3.csv

### **Variables**
For variables that need to be linked to SVO, please provide variable's name (as it appears in the data file), its description, and its type (categorical or numerical).

1. Time:
   - _description_: time of satellite imagery acquisition used for estimating river width and depth
   - _type_: categorical and string
2. River_Width:
   - _description_: measures the width (in meters) of the river along a cross section
   - _type_: numerical 
3. River_Depth:
   - _description_: measures the depth (in meters) of the river along a cross section
   - _type_: numerical

**Comment by mariutzica** [comment]
@ankushkhandelwal Here are the variable names for your dataset. I provided some explanations as well as possible clarifications below:

Time:
- description: time of satellite imagery acquisition used for estimating river width and depth
- type: categorical and string
- SVO label: ```event__observation_time```
River_Width:
- description: measures the width (in meters) of the river along a cross section
- type: numerical
- SVO label: ```channel~river_water_x-section__width```
River_Depth:
- description: measures the depth (in meters) of the river along a cross section
- type: numerical
- SVO label: ```channel~river_water_x-section__depth```

Explanation:
1. ```event__observation_time``` this is the universal time for the dataset and all observations "events" made at this time
2 + 3. Channel is the general term used to describe the desired landform, and river is the type of channel (~denotes taxonomic relationship). Depth and width are both types of "length". Unless the cross section is assumed to be rectangular, it may be helpful to specify which depth and which width -- e.g.,
```channel~river_water_x-section_top__width``` and
```channel~river_water_x-section__max_of_depth```
If it is rectangular, you may want to specify it like this:
```channel~river_water_x-section_rectangle__width```

**Comment by ankushkhandelwal** [comment]
Hey! Could you also please provide the uri for these variables

**Comment by mariutzica** [comment]
Hi @ankushkhandelwal , the variables were not already in the ontology, so I temporarily generated their IRIs and included them above. If you agree with these labels, I will go ahead and add them to the official SVO.

**Comment by ankushkhandelwal** [comment]
Hi @mariutzica 
Please add these two variables -
channel~river_water_x-section_top__width
channel~river_water_x-section__max_of_depth

I am assuming the uris will change as well because the ones that we have right now don't incorporate top and max keywords in them.

**Comment by mariutzica** [comment]
@ankushkhandelwal I just added the URIs to the previous post. I will add them to SVO as well. There may be a delay before they are up on the SPARQL endpoint, but you should be able to register them in the data catalog at any time.
